# Generated by ariadne-codegen on 2023-09-11 17:39
# Source: gql/gitlab

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel


class PrStats(BaseModel):
    project: Optional["PrStatsProject"]


class PrStatsProject(BaseModel):
    merge_requests: Optional["PrStatsProjectMergeRequests"] = Field(alias="mergeRequests")


class PrStatsProjectMergeRequests(BaseModel):
    edges: Optional[List[Optional["PrStatsProjectMergeRequestsEdges"]]]


class PrStatsProjectMergeRequestsEdges(BaseModel):
    node: Optional["PrStatsProjectMergeRequestsEdgesNode"]


class PrStatsProjectMergeRequestsEdgesNode(BaseModel):
    id: str
    title: str
    created_at: Any = Field(alias="createdAt")
    merged_at: Optional[Any] = Field(alias="mergedAt")
    author: Optional["PrStatsProjectMergeRequestsEdgesNodeAuthor"]
    notes: "PrStatsProjectMergeRequestsEdgesNodeNotes"
    diff_stats: Optional[List["PrStatsProjectMergeRequestsEdgesNodeDiffStats"]] = Field(alias="diffStats")


class PrStatsProjectMergeRequestsEdgesNodeAuthor(BaseModel):
    username: str


class PrStatsProjectMergeRequestsEdgesNodeNotes(BaseModel):
    edges: Optional[List[Optional["PrStatsProjectMergeRequestsEdgesNodeNotesEdges"]]]


class PrStatsProjectMergeRequestsEdgesNodeNotesEdges(BaseModel):
    node: Optional["PrStatsProjectMergeRequestsEdgesNodeNotesEdgesNode"]


class PrStatsProjectMergeRequestsEdgesNodeNotesEdgesNode(BaseModel):
    author_is_contributor: Optional[bool] = Field(alias="authorIsContributor")
    created_at: Any = Field(alias="createdAt")
    discussion: Optional["PrStatsProjectMergeRequestsEdgesNodeNotesEdgesNodeDiscussion"]


class PrStatsProjectMergeRequestsEdgesNodeNotesEdgesNodeDiscussion(BaseModel):
    id: Any


class PrStatsProjectMergeRequestsEdgesNodeDiffStats(BaseModel):
    additions: int
    deletions: int
    path: str


PrStats.model_rebuild()
PrStatsProject.model_rebuild()
PrStatsProjectMergeRequests.model_rebuild()
PrStatsProjectMergeRequestsEdges.model_rebuild()
PrStatsProjectMergeRequestsEdgesNode.model_rebuild()
PrStatsProjectMergeRequestsEdgesNodeAuthor.model_rebuild()
PrStatsProjectMergeRequestsEdgesNodeNotes.model_rebuild()
PrStatsProjectMergeRequestsEdgesNodeNotesEdges.model_rebuild()
PrStatsProjectMergeRequestsEdgesNodeNotesEdgesNode.model_rebuild()
PrStatsProjectMergeRequestsEdgesNodeNotesEdgesNodeDiscussion.model_rebuild()
PrStatsProjectMergeRequestsEdgesNodeDiffStats.model_rebuild()
